import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Provider from "./Provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Đặt vé xem phim",
  description: "Generated by create next app",
  // icons: {
  //   icon: "logo.png",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <div>{children}</div>
        <Toaster />
        </Provider>
      </body>
    </html>
  );
}
